apiVersion: batch/v1
kind: Job
metadata:
  name: stackrox-policy-copy-all
  namespace: stackrox
spec:
  template:
    metadata:
      name: stackrox-policy-copy-all-job
    spec:
      containers:
        - name: stackrox-policy-copy-all-job
          env:
          - name: ROX_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: rox-api-token
                key: token
          - name: ROX_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: rox-central-address
                key: address
          # Decide b/t one of these two
          # image: registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel8:3.71.2
          image: registry.access.redhat.com/ubi8/ubi:8.3-297
          imagePullPolicy: IfNotPresent
          script: |
            yum install jq -y -q
            yum install curl -y -q

            echo ${ROX_ENDPOINT}
            echo ${ROX_API_TOKEN}
      restartPolicy: OnFailure
